sudo: required
services:
  - docker
before_install:
  - docker build -t ci --build-arg RELAY2I_WEB3_URL=$RELAY2I_WEB3_URL --build-arg RELAY2I_KEYSTORE_PASSWORD=$RELAY2I_KEYSTORE_PASSWORD    . 
script:
  - docker images ci
