server:
  serviceapi: 0.0.0.0:8000
  adminapi: 0.0.0.0:8001

web3:
  url:
      
keystore:
  path: ./keystore
  address: 0xe0fbce58cfaa72812103f003adce3f284fe5fc7c
  password:
  
contracts:
  rootcommits:
    jsonabi: ./compiled-contracts/RootCommits.json
    address: 0x6A6E04938d66Df5717ec4774E0ca181077e842ed
  iden3impl:
    jsonabi: ./compiled-contracts/IDen3Impl.json
    address: 0x66D0c2F85F1B717168cbB508AfD1c46e07227130
  iden3deployer:
    jsonabi: ./compiled-contracts/Deployer.json
    address: 0xf02e236F9F6C08966DD63B9fB9C04764E01b0563
  iden3proxy: 
    jsonabi: ./compiled-contracts/IDen3DelegateProxy.json

storage:
  path: /tmp/treedb

domain: iden3.io
namespace: iden3.io